### ISSUE TITLE
Stable version

### ISSUE THREAD

**Issue by Firesphere** [silverstripe-labs/silverstripe-gridfieldajaxrefresh#5]
When will a first release of this be made?

Composer breaks on stability stable if this module is required.

**Comment by candidasa** [comment]
I've updated the composer.json requirements. This should now work:

composer require "silverstripe/gridfieldajaxrefresh":*

**Comment by Firesphere** [comment]
Yes, works. Not entirely the preferred solution, but good enough for now :)
